- name: Play1
  hosts: web
  tasks:
  - name: Play1 and Task1
    ansible.builtin.debug:
      msg: "Hello I am from Play1 and Task1"


- name: Play2
  hosts: web
  tasks:
  - name: Play1 and Task1
    ansible.builtin.debug:
      msg: "Hello I am from Play2 and Task1"