- name: Play1
  hosts: 172.31.21.203
  tasks:
  - name: Play1 and Task1
    ansible.builtin.debug:
      msg: "Hello I am from Play1 and Task1"

- name: Play2
  hosts: 172.31.21.203
  tasks:
  - name: Play2 and Task1
    ansible.builtin.debug:
    msg: "Hello I am from Play2 and Task1"