- name: Variable Preferences
  hosts: web
  vars:
    WISHES: "Morning from Play Variable"
  vars_files:
  - vars.yml
  vars_prompt:
  - name: WISHES
    Prompt: Please enter WISHES
    private: false
  tasks:
  - name: Check Preference
    vars:
      WISHES: "Morning from TASK Variable"
    ansible.builtin.debug:
      msg: "Hello, Good{{WISHES}}"
