- name: Conditions
  hosts: web
  become: yes
  tasks:
  - name: Check User exists or not
    ansible.builtin.command: id expense
    ignore_errors: true

  - name: Print
    ansible.builtin.debug:
      msg: "Print Hello"