- name: Check number 
  hosts: localhost
  vars_prompt:
  - name: number
    prompt: please enter number
    private: no
  tasks:
  - name: number less than 10
    ansible.builtin.debug:
      msg: "Given number {{number}} is less than 10"
    when: number | int < 10
  
  - name: number greater than or equal to10
    ansible.builtin.debug:
      msg: "Given number {{number}} is greater or equal to 10"
    when: number | int >= 10