- name: default value
  hosts: localhost
  tasks:
  - name: print default value
    ansible.builtin.debug:
      msg: "Hello {{course | default('ANSIBLE') | lower}}"

- name: Upper case
  hosts: localhost
  vars:
    greeting: Hello, Good Morning
  tasks:
  - name: Print UpperCase
    ansible.builtin.debug:
      msg: "{{greeting | upper}}"

- name: Lower Case
  hosts: localhost
  vars:
    greet: KHYATHI PAPA
  tasks:
  - name: Lower Case
    ansible.builtin.debug:
      msg: "{{greet | lower}}"

- name: Remove Duplicates
  hosts: localhost
  vars:
    numbers: [1, 3, 4, 2, 3, 4, 5, 5, 4, 6, 6]
  tasks:
  - name: remove duplicates
    ansible.builtin.debug:
      msg: "{{numbers | unique }}"

- name: min and max
  hosts: localhost
  vars:
    age: [24, 2, 27, 31]
  tasks:
  - name: min and max
    ansible.builtin.debug:
      msg: Min_age is "{{age | min }}, Max_age is "{{age | max }}"

- name: Convert dictionary into items
  hosts: localhost
  vars:
    my_dict:
      Course: Ansible
      Trainer: Siva
      Duration: 120Hrs
  tasks:
  - name: Before Conversion
    ansible.builtin.debug:
      msg: "Before Conversion: {{my_dict}}"
      
  - name: After Conversion
    ansible.builtin.debug:
      msg: "After Conversion: {{my_dict | dict2items}}"